package com.example.ritsu.ui.components

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.tooling.preview.Preview
import com.example.ritsu.ui.cards.*
import com.example.ritsu.ui.theme.RitsuTheme

@Composable
fun SummaryExportContent(
    dateRange: String,
    topGames: List<TopGameItem>,
    topCharts: List<TopScoreItem>,
    topScores: List<TopScoreItem>,
    activityData: List<ActivityDataPoint>,
    modifier: Modifier = Modifier,
) {
    val backgroundColor = MaterialTheme.colorScheme.background
    
    Box(
        modifier = modifier
            .aspectRatio(1f)
            .background(backgroundColor)
            .padding(24.dp) // More padding for a premium look with 4 entries
    ) {
        Column(
            modifier = Modifier.fillMaxSize(),
            horizontalAlignment = Alignment.CenterHorizontally
        ) {
            // Header with Date Range
            Text(
                text = dateRange,
                style = MaterialTheme.typography.titleMedium,
                color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.6f),
                modifier = Modifier.padding(bottom = 16.dp)
            )

            // Top Row: Games and Charts
            Row(
                modifier = Modifier.weight(1.1f),
                horizontalArrangement = Arrangement.spacedBy(16.dp)
            ) {
                ExportCardWrapper(title = "Top Games", modifier = Modifier.weight(1f)) {
                    Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                        topGames.take(4).forEach { game ->
                            GameListItem(game, isCompact = true) {}
                        }
                    }
                }
                
                ExportCardWrapper(title = "Top Charts", modifier = Modifier.weight(1f)) {
                    Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                        topCharts.take(4).forEach { score ->
                            ScoreListItem(score, selectedSort = "Plays", isCompact = true) {}
                        }
                    }
                }
            }

            Spacer(modifier = Modifier.height(16.dp))

            // Bottom Section: Top Scores (Full Width)
            ExportCardWrapper(title = "Top Scores", modifier = Modifier.weight(1f)) {
                Column(verticalArrangement = Arrangement.spacedBy(8.dp)) {
                    topScores.take(4).forEach { score ->
                        ScoreListItem(score, selectedSort = "Accuracy", isCompact = true) {}
                    }
                }
            }
            
            // Branding Footer
            Row(
                modifier = Modifier.padding(top = 20.dp),
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.spacedBy(4.dp)
            ) {
                Text(
                    text = "Generated by Ritsu",
                    style = MaterialTheme.typography.labelLarge,
                    fontWeight = FontWeight.Bold,
                    color = MaterialTheme.colorScheme.primary.copy(alpha = 0.7f)
                )
            }
        }
    }
}

@Composable
fun ExportCardWrapper(
    title: String,
    modifier: Modifier = Modifier,
    content: @Composable () -> Unit
) {
    Surface(
        color = MaterialTheme.colorScheme.surface,
        shape = RoundedCornerShape(16.dp),
        shadowElevation = 2.dp,
        modifier = modifier.fillMaxWidth()
    ) {
        Column(modifier = Modifier.padding(14.dp)) {
            Text(
                text = title,
                style = MaterialTheme.typography.titleMedium,
                fontWeight = FontWeight.ExtraBold,
                color = MaterialTheme.colorScheme.primary,
                modifier = Modifier.padding(bottom = 10.dp)
            )
            content()
        }
    }
}

@Preview(showBackground = true, widthDp = 1080, heightDp = 1080)
@Composable
fun SummaryExportContentSquarePreview() {
    RitsuTheme {
        SummaryExportContent(
            dateRange = "Jan 1, 2024 - Dec 31, 2024",
            topGames = (1..4).map { 
                TopGameItem(
                    rank = it, 
                    gameName = "Game $it", 
                    playCount = 100 - it, 
                    displayIconUri = null,
                    achievements = listOf("Full Combo" to 1)
                ) 
            },
            topCharts = (1..4).map { 
                TopScoreItem(scoreId = it.toLong(), rank = it, songTitle = "Song $it", difficultyName = "Expert", difficultyVal = "2$it", accuracy = 99.0, maxCombo = 1000, playRank = "S", gameName = "Game A", totalScore = 1000000, playCount = 10, booleanLabels = emptyList(), showRank = true, showIcon = true, displayIconUri = null) 
            },
            topScores = (1..4).map { 
                TopScoreItem(
                    scoreId = it.toLong() + 10, 
                    rank = it, 
                    songTitle = "Score Song $it", 
                    difficultyName = "Master", 
                    difficultyVal = "3$it", 
                    accuracy = 100.0, 
                    maxCombo = 2000, 
                    playRank = "P", 
                    gameName = "Game B", 
                    totalScore = 2000000, 
                    playCount = 1, 
                    booleanLabels = listOf("FC", "AP"), 
                    showRank = true, 
                    showIcon = true, 
                    displayIconUri = null
                )
            },
            activityData = listOf()
        )
    }
}
