package com.example.ritsu.ui.components

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.tooling.preview.Preview
import com.example.ritsu.ui.cards.*
import com.example.ritsu.ui.theme.RitsuTheme

@Composable
fun SummaryExportContent(
    dateRange: String,
    topGames: List<TopGameItem>,
    topCharts: List<TopScoreItem>,
    topScores: List<TopScoreItem>,
    activityData: List<ActivityDataPoint>,
    aspectRatio: String = "4:3",
    modifier: Modifier = Modifier,
) {
    val backgroundColor = MaterialTheme.colorScheme.background
    val isSquare = aspectRatio == "Square"
    
    // Calculate size based on aspect ratio
    val contentModifier = if (isSquare) {
        Modifier.aspectRatio(1f)
    } else {
        Modifier.aspectRatio(4f / 3f)
    }

    Box(
        modifier = modifier
            .then(contentModifier)
            .background(backgroundColor)
            .padding(if (isSquare) 16.dp else 12.dp)
    ) {
        Column(
            modifier = Modifier.fillMaxSize(),
            horizontalAlignment = Alignment.CenterHorizontally
        ) {
            // Header with Date Range
            Text(
                text = dateRange,
                style = MaterialTheme.typography.titleMedium,
                color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.6f),
                modifier = Modifier.padding(bottom = 8.dp)
            )

            // Top Row: Games and Charts
            Row(
                modifier = Modifier.weight(1f),
                horizontalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                ExportCardWrapper(title = "Top Games", modifier = Modifier.weight(1f)) {
                    Column(verticalArrangement = Arrangement.spacedBy(4.dp)) {
                        topGames.take(if (isSquare) 5 else 4).forEach { game ->
                            GameListItem(game) {}
                        }
                    }
                }
                
                ExportCardWrapper(title = "Top Charts", modifier = Modifier.weight(1f)) {
                    Column(verticalArrangement = Arrangement.spacedBy(4.dp)) {
                        topCharts.take(if (isSquare) 5 else 4).forEach { score ->
                            ScoreListItem(score, selectedSort = "Plays") {}
                        }
                    }
                }
            }

            Spacer(modifier = Modifier.height(8.dp))

            // Bottom Section: Top Scores (Full Width for more space)
            ExportCardWrapper(title = "Top Scores", modifier = Modifier.weight(1f)) {
                Column(verticalArrangement = Arrangement.spacedBy(4.dp)) {
                    topScores.take(if (isSquare) 6 else 5).forEach { score ->
                        ScoreListItem(score, selectedSort = "Accuracy") {}
                    }
                }
            }
            
            // Branding Footer
            Row(
                modifier = Modifier.padding(top = 12.dp),
                verticalAlignment = Alignment.CenterVertically,
                horizontalArrangement = Arrangement.spacedBy(4.dp)
            ) {
                Text(
                    text = "Generated by Ritsu",
                    style = MaterialTheme.typography.labelMedium,
                    fontWeight = FontWeight.Medium,
                    color = MaterialTheme.colorScheme.primary.copy(alpha = 0.7f)
                )
            }
        }
    }
}

@Composable
fun ExportCardWrapper(
    title: String,
    modifier: Modifier = Modifier,
    content: @Composable () -> Unit
) {
    Surface(
        color = MaterialTheme.colorScheme.surface,
        shape = RoundedCornerShape(12.dp),
        shadowElevation = 2.dp,
        modifier = modifier.fillMaxWidth()
    ) {
        Column(modifier = Modifier.padding(8.dp)) {
            Text(
                text = title,
                style = MaterialTheme.typography.labelLarge,
                fontWeight = FontWeight.Bold,
                color = MaterialTheme.colorScheme.secondary,
                modifier = Modifier.padding(bottom = 4.dp)
            )
            content()
        }
    }
}

@Preview(showBackground = true, widthDp = 1080, heightDp = 810)
@Composable
fun SummaryExportContentPreview() {
    RitsuTheme {
        SummaryExportContent(
            dateRange = "Jan 1, 2024 - Dec 31, 2024",
            topGames = listOf(),
            topCharts = listOf(),
            topScores = listOf(),
            activityData = listOf(),
            aspectRatio = "4:3"
        )
    }
}

@Preview(showBackground = true, widthDp = 1080, heightDp = 1080)
@Composable
fun SummaryExportContentSquarePreview() {
    RitsuTheme {
        SummaryExportContent(
            dateRange = "Jan 1, 2024 - Dec 31, 2024",
            topGames = listOf(),
            topCharts = listOf(),
            topScores = listOf(),
            activityData = listOf(),
            aspectRatio = "Square"
        )
    }
}
